FROM ruby:2.7-alpine

ARG PRIVATE_KEY
ARG APP_IDENTIFIER
ARG WEBHOOK_SECRET

WORKDIR /server
COPY ./Gem* /server/
COPY ./*.rb /server/

RUN gem install bundler
RUN bundle install

ENV GITHUB_PRIVATE_KEY=${PRIVATE_KEY}
ENV GITHUB_APP_IDENTIFIER=${APP_IDENTIFIER}
ENV GITHUB_WEBHOOK_SECRET=${WEBHOOK_SECRET}

EXPOSE 3000
ENTRYPOINT exec ruby server.rb
