name: Publish Bot container image

on:
  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Verify Server Code
      run: echo TO DO

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag guac-pr-bot:latest --tag prbotimages.azurecr.io/guac/guac-pr-bot:$(date +%s) --tag prbotimages.azurecr.io/guac/guac-pr-bot:latest

    - name: Publish to Azure Container Registry
      run: |
        echo Publishing...
        # docker login prbotimages.azurecr.io -u PrBotImages -p SECRET
        # docker push prbotimages.azurecr.io/guac/guac-pr-bot:latest

    - name: Verify deployment
      run: |
        # curl -w '%{http_code}' http://guac-pr-bot.azurewebsites.net/event_handler | grep 200
        curl http://guac-pr-bot.azurewebsites.net/event_handler | grep Healthy
        # This should return a non-zero $? if there wasn't a found