name: Publish Bot container image

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t guac-pr-bot:latest -t prbotimages.azurecr.io/guac/guac-pr-bot:$(date +%s) -t prbotimages.azurecr.io/guac/guac-pr-bot:latest --build-arg PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" --build-arg APP_IDENTIFIER="${{ secrets.APP_IDENTIFIER }}" --build-arg WEBHOOK_SECRET="${{ secrets.WEBHOOK_SECRET }}"

    - name: Container smoke test
      run: |
        # echo ${{ secrets.PRIVATE_KEY }} | cut -c1-60
        docker run -p 3000:3000 guac-pr-bot:latest &
        sleep 2s
        curl http://localhost:3000/event_handler > /tmp/container_verify.log
        docker rm -f `docker ps -a --format "{{ .ID }}"` 
        cat /tmp/container_verify.log
        grep Healthy /tmp/container_verify.log

    - name: Publish to Azure Container Registry
      run: |
        echo Publishing...
        docker login prbotimages.azurecr.io -u ${{ secrets.CONTAINER_LOGIN }} -p ${{ secrets.CONTAINER_PASSWORD }}
        docker push prbotimages.azurecr.io/guac/guac-pr-bot:latest prbotimages.azurecr.io/guac/guac-pr-bot:$(date +%s)
